import { PrismaClient } from '@prisma/client';
import fs from 'fs';
import path from 'path';

const prisma = new PrismaClient();

export interface MasterFoodItem {
  name: string;
  category: string;
  subcategory?: string;
  country: string;
  caloriesPer100: number;
  proteinPer100: number;
  carbsPer100: number;
  fatPer100: number;
  fiberPer100: number;
  servingUnits: string;
  isIndian: boolean;
  isVeg: boolean;
  notes?: string;
}

import { MASTER_FOODS as existingFoods } from '../lib/nutrition/master-foods-data';

const expansionFoods: MasterFoodItem[] = [
  // --- INDIA EXPANSION ---
  {
    name: 'Kadai Paneer (Capsicum & Cottage Cheese)',
    category: 'Indian Dishes',
    subcategory: 'Curry',
    country: 'India',
    caloriesPer100: 215,
    proteinPer100: 9.5,
    carbsPer100: 7.2,
    fatPer100: 16.5,
    fiberPer100: 2.8,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'bowl', multiplier: 2.0 }, { unit: 'serving', multiplier: 1.8 }]),
    isIndian: true,
    isVeg: true,
    notes: 'Paneer and crunchy bell peppers tossed in spicy freshly ground kadai masala.',
  },
  {
    name: 'Matar Paneer (Peas & Cottage Cheese)',
    category: 'Indian Dishes',
    subcategory: 'Curry',
    country: 'India',
    caloriesPer100: 175,
    proteinPer100: 8.2,
    carbsPer100: 10.5,
    fatPer100: 11.0,
    fiberPer100: 3.2,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'bowl', multiplier: 2.0 }]),
    isIndian: true,
    isVeg: true,
    notes: 'Tender green peas and paneer cubes simmered in spiced onion-tomato gravy.',
  },
  {
    name: 'Malai Kofta (Cottage Cheese Dumplings in Cream Gravy)',
    category: 'Indian Dishes',
    subcategory: 'Curry',
    country: 'India',
    caloriesPer100: 255,
    proteinPer100: 6.2,
    carbsPer100: 16.0,
    fatPer100: 18.5,
    fiberPer100: 2.1,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'bowl', multiplier: 2.2 }]),
    isIndian: true,
    isVeg: true,
    notes: 'Crispy potato-paneer dumplings in velvet cashew and cream curry.',
  },
  {
    name: 'Aloo Gobi (Spiced Potato & Cauliflower)',
    category: 'Indian Dishes',
    subcategory: 'Sabzi',
    country: 'India',
    caloriesPer100: 110,
    proteinPer100: 2.8,
    carbsPer100: 16.0,
    fatPer100: 4.2,
    fiberPer100: 3.5,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'bowl', multiplier: 1.8 }]),
    isIndian: true,
    isVeg: true,
    notes: 'Classic dry curry of potatoes and cauliflower florets with turmeric and cumin.',
  },
  {
    name: 'Bhindi Masala (Spiced Okra / Ladyfinger)',
    category: 'Indian Dishes',
    subcategory: 'Sabzi',
    country: 'India',
    caloriesPer100: 95,
    proteinPer100: 2.4,
    carbsPer100: 11.5,
    fatPer100: 4.5,
    fiberPer100: 4.2,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'bowl', multiplier: 1.8 }]),
    isIndian: true,
    isVeg: true,
    notes: 'Stir-fried okra with sliced onions, amchur (dry mango) powder and garam masala.',
  },
  {
    name: 'Baingan Bharta (Smoked Roasted Eggplant)',
    category: 'Indian Dishes',
    subcategory: 'Sabzi',
    country: 'India',
    caloriesPer100: 85,
    proteinPer100: 2.0,
    carbsPer100: 8.5,
    fatPer100: 5.0,
    fiberPer100: 3.8,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'bowl', multiplier: 1.8 }]),
    isIndian: true,
    isVeg: true,
    notes: 'Char-roasted eggplant mashed with tomatoes, green chillies, garlic and mustard oil.',
  },
  {
    name: 'Mutton Rogan Josh (Kashmiri Lamb Curry)',
    category: 'Indian Dishes',
    subcategory: 'Meat',
    country: 'India',
    caloriesPer100: 220,
    proteinPer100: 16.5,
    carbsPer100: 3.5,
    fatPer100: 15.8,
    fiberPer100: 1.0,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'bowl', multiplier: 2.2 }]),
    isIndian: true,
    isVeg: false,
    notes: 'Slow-cooked tender lamb in an aromatic Kashmiri red chilli and fennel gravy.',
  },
  {
    name: 'Kerala Fish Curry (Kudampuli & Coconut)',
    category: 'Indian Dishes',
    subcategory: 'Fish',
    country: 'India',
    caloriesPer100: 145,
    proteinPer100: 16.0,
    carbsPer100: 3.2,
    fatPer100: 7.5,
    fiberPer100: 0.8,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'bowl', multiplier: 2.0 }]),
    isIndian: true,
    isVeg: false,
    notes: 'Fresh sea fish simmered with Malabar tamarind (kodampuli), coconut and curry leaves.',
  },
  {
    name: 'Paneer Tikka (Tandoori Grilled)',
    category: 'Indian Dishes',
    subcategory: 'Tandoor',
    country: 'India',
    caloriesPer100: 240,
    proteinPer100: 14.5,
    carbsPer100: 6.0,
    fatPer100: 18.0,
    fiberPer100: 1.5,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'piece', multiplier: 0.35 }, { unit: 'serving', multiplier: 1.8 }]),
    isIndian: true,
    isVeg: true,
    notes: 'Skewered cottage cheese cubes marinated in yogurt and tandoori spices, grilled over coals.',
  },
  {
    name: 'Chicken Reshmi Kebab (Mughlai Malai Kebab)',
    category: 'Indian Dishes',
    subcategory: 'Meat',
    country: 'India',
    caloriesPer100: 190,
    proteinPer100: 23.5,
    carbsPer100: 3.0,
    fatPer100: 9.5,
    fiberPer100: 0.2,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'serving', multiplier: 1.5 }]),
    isIndian: true,
    isVeg: false,
    notes: 'Silky chicken breast skewers marinated with cashew paste, cream, and white pepper.',
  },
  {
    name: 'Methi Thepla (Fenugreek Flatbread)',
    category: 'Indian Dishes',
    subcategory: 'Breads',
    country: 'India',
    caloriesPer100: 260,
    proteinPer100: 8.5,
    carbsPer100: 42.0,
    fatPer100: 7.2,
    fiberPer100: 6.5,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'piece', multiplier: 0.40 }]),
    isIndian: true,
    isVeg: true,
    notes: 'Gujarati spiced flatbread made with whole wheat, gram flour and fresh fenugreek leaves (~105 kcal).',
  },
  {
    name: 'Jeera Rice (Cumin Basmati Rice)',
    category: 'Indian Dishes',
    subcategory: 'Rice',
    country: 'India',
    caloriesPer100: 145,
    proteinPer100: 2.8,
    carbsPer100: 28.5,
    fatPer100: 2.2,
    fiberPer100: 0.8,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'bowl', multiplier: 1.8 }]),
    isIndian: true,
    isVeg: true,
    notes: 'Aromatic basmati rice tempered with toasted cumin seeds and a touch of desi ghee.',
  },
  {
    name: 'Ven Pongal (South Indian Ghee Rice & Lentils)',
    category: 'Indian Dishes',
    subcategory: 'Breakfast',
    country: 'India',
    caloriesPer100: 165,
    proteinPer100: 4.8,
    carbsPer100: 24.0,
    fatPer100: 5.8,
    fiberPer100: 2.0,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'bowl', multiplier: 2.0 }]),
    isIndian: true,
    isVeg: true,
    notes: 'Traditional Tamil breakfast of rice and yellow moong dal tempered with crushed black pepper, cumin and cashews.',
  },
  {
    name: 'Onion Uttapam',
    category: 'Indian Dishes',
    subcategory: 'Breakfast',
    country: 'India',
    caloriesPer100: 170,
    proteinPer100: 4.5,
    carbsPer100: 29.0,
    fatPer100: 4.2,
    fiberPer100: 2.2,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'piece', multiplier: 1.2 }]),
    isIndian: true,
    isVeg: true,
    notes: 'Thick fermented rice-lentil pancake topped with diced red onions, curry leaves and green chillies (~200 kcal).',
  },
  {
    name: 'Coconut Chutney (Fresh Grated)',
    category: 'Indian Dishes',
    subcategory: 'Chutneys',
    country: 'India',
    caloriesPer100: 210,
    proteinPer100: 3.5,
    carbsPer100: 7.5,
    fatPer100: 19.0,
    fiberPer100: 5.5,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'tablespoon', multiplier: 0.25 }, { unit: 'bowl', multiplier: 0.60 }]),
    isIndian: true,
    isVeg: true,
    notes: 'Fresh coconut ground with roasted chana dal, ginger, and tempered with mustard seeds.',
  },
  {
    name: 'Sprouted Moong Salad (Kala Chana & Green Gram)',
    category: 'Indian Dishes',
    subcategory: 'Salad',
    country: 'India',
    caloriesPer100: 120,
    proteinPer100: 8.8,
    carbsPer100: 18.0,
    fatPer100: 1.2,
    fiberPer100: 6.5,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'bowl', multiplier: 1.5 }]),
    isIndian: true,
    isVeg: true,
    notes: 'Raw sprouted legumes tossed with lemon juice, chaat masala, cucumber, tomato and fresh coriander.',
  },
  {
    name: 'Roasted Phool Makhana (Spiced Foxnuts)',
    category: 'Indian Dishes',
    subcategory: 'Snacks',
    country: 'India',
    caloriesPer100: 350,
    proteinPer100: 9.7,
    carbsPer100: 64.0,
    fatPer100: 5.0,
    fiberPer100: 7.6,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'bowl', multiplier: 0.35 }]),
    isIndian: true,
    isVeg: true,
    notes: 'Low-calorie crunchy lotus seeds roasted in light ghee with black pepper and pink salt (~120 kcal per full bowl).',
  },
  {
    name: 'Khaman Dhokla (Steamed Gram Flour Cakes)',
    category: 'Indian Dishes',
    subcategory: 'Breakfast',
    country: 'India',
    caloriesPer100: 155,
    proteinPer100: 6.5,
    carbsPer100: 24.5,
    fatPer100: 3.5,
    fiberPer100: 2.8,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'piece', multiplier: 0.40 }]),
    isIndian: true,
    isVeg: true,
    notes: 'Fluffy steamed besan cakes tempered with mustard seeds, sesame seeds and green chillies (~62 kcal per piece).',
  },
  {
    name: 'Bhel Puri (Puffed Rice Chaat)',
    category: 'Indian Dishes',
    subcategory: 'Street Food',
    country: 'India',
    caloriesPer100: 195,
    proteinPer100: 4.5,
    carbsPer100: 35.0,
    fatPer100: 4.8,
    fiberPer100: 3.2,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'plate', multiplier: 1.8 }]),
    isIndian: true,
    isVeg: true,
    notes: 'Puffed rice tossed with onions, boiled potatoes, sev and sweet tamarind-date chutney.',
  },
  {
    name: 'Gulab Jamun (2 pieces in Sugar Syrup)',
    category: 'Snacks',
    subcategory: 'Sweets',
    country: 'India',
    caloriesPer100: 325,
    proteinPer100: 5.2,
    carbsPer100: 52.0,
    fatPer100: 11.5,
    fiberPer100: 0.5,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'piece', multiplier: 0.45 }, { unit: 'serving', multiplier: 0.90 }]),
    isIndian: true,
    isVeg: true,
    notes: 'Deep-fried milk solid (khoya) dumplings soaked in rose and cardamom sugar syrup (~145 kcal per piece).',
  },

  // --- USA & GYM STAPLES EXPANSION ---
  {
    name: 'Lean Bison Patty (90/10)',
    category: 'Protein',
    subcategory: 'Meat',
    country: 'United States',
    caloriesPer100: 175,
    proteinPer100: 26.0,
    carbsPer100: 0.0,
    fatPer100: 8.0,
    fiberPer100: 0.0,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'patty', multiplier: 1.15 }]),
    isIndian: false,
    isVeg: false,
    notes: 'Super-lean red meat packed with iron and creatine; leaner than conventional beef.',
  },
  {
    name: 'Turkey Bacon (Cooked Crisp)',
    category: 'Protein',
    subcategory: 'Poultry',
    country: 'United States',
    caloriesPer100: 382,
    proteinPer100: 30.0,
    carbsPer100: 3.5,
    fatPer100: 28.0,
    fiberPer100: 0.0,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'strip', multiplier: 0.15 }]),
    isIndian: false,
    isVeg: false,
    notes: 'Lower fat breakfast alternative to pork bacon (~57 kcal, 4.5g protein per strip).',
  },
  {
    name: 'Baked Tilapia Fillet',
    category: 'Protein',
    subcategory: 'Fish',
    country: 'United States',
    caloriesPer100: 128,
    proteinPer100: 26.0,
    carbsPer100: 0.0,
    fatPer100: 2.7,
    fiberPer100: 0.0,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'fillet', multiplier: 1.2 }]),
    isIndian: false,
    isVeg: false,
    notes: 'Mild white fish staple for contest prep; nearly zero fat or carbs.',
  },
  {
    name: 'Pacific Cod Fillet (Steamed / Baked)',
    category: 'Protein',
    subcategory: 'Fish',
    country: 'United States',
    caloriesPer100: 82,
    proteinPer100: 18.0,
    carbsPer100: 0.0,
    fatPer100: 0.7,
    fiberPer100: 0.0,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'fillet', multiplier: 1.5 }]),
    isIndian: false,
    isVeg: false,
    notes: 'One of the leanest fish species on Earth with less than 1g of fat per serving.',
  },
  {
    name: 'Micellar Casein Protein Powder',
    category: 'Protein',
    subcategory: 'Supplements',
    country: 'United States',
    caloriesPer100: 365,
    proteinPer100: 82.0,
    carbsPer100: 3.5,
    fatPer100: 1.5,
    fiberPer100: 1.0,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'scoop', multiplier: 0.33 }]),
    isIndian: false,
    isVeg: true,
    notes: 'Slow-digesting nighttime protein providing sustained amino acid delivery over 7-8 hours.',
  },
  {
    name: 'Plain Whole Grain Rice Cakes',
    category: 'Carbohydrates',
    subcategory: 'Snacks',
    country: 'United States',
    caloriesPer100: 387,
    proteinPer100: 8.0,
    carbsPer100: 82.0,
    fatPer100: 2.8,
    fiberPer100: 4.2,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'piece', multiplier: 0.09 }]),
    isIndian: false,
    isVeg: true,
    notes: 'Convenient zero-fat carb delivery vehicle; 1 rice cake (~9g) is ~35 kcal, ideal pre-workout.',
  },
  {
    name: 'Artisan Sourdough Bread Slice',
    category: 'Carbohydrates',
    subcategory: 'Breads',
    country: 'United States',
    caloriesPer100: 245,
    proteinPer100: 9.0,
    carbsPer100: 48.0,
    fatPer100: 1.2,
    fiberPer100: 3.0,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'slice', multiplier: 0.50 }]),
    isIndian: false,
    isVeg: true,
    notes: 'Naturally fermented bread with wild yeast; lower glycemic impact and prebiotic benefits.',
  },
  {
    name: 'Plain New York Style Bagel',
    category: 'Carbohydrates',
    subcategory: 'Breads',
    country: 'United States',
    caloriesPer100: 257,
    proteinPer100: 10.0,
    carbsPer100: 50.0,
    fatPer100: 1.5,
    fiberPer100: 2.5,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'piece', multiplier: 1.05 }]),
    isIndian: false,
    isVeg: true,
    notes: 'Dense, chewy boiled-then-baked roll; prime carb load fuel (~270 kcal per bagel).',
  },
  {
    name: 'Whole Wheat Protein Pancakes',
    category: 'Carbohydrates',
    subcategory: 'Breakfast',
    country: 'United States',
    caloriesPer100: 185,
    proteinPer100: 14.5,
    carbsPer100: 24.0,
    fatPer100: 3.2,
    fiberPer100: 3.5,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'piece', multiplier: 0.75 }]),
    isIndian: false,
    isVeg: true,
    notes: 'Fluffy griddle cakes fortified with whey protein and whole oat flour.',
  },
  {
    name: 'Baked Russet Potato (Plain with Skin)',
    category: 'Carbohydrates',
    subcategory: 'Tubers',
    country: 'United States',
    caloriesPer100: 93,
    proteinPer100: 2.5,
    carbsPer100: 21.2,
    fatPer100: 0.1,
    fiberPer100: 2.2,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'piece', multiplier: 2.0 }]),
    isIndian: false,
    isVeg: true,
    notes: 'Highest satiety index of any carbohydrate source on Earth; packed with potassium.',
  },
  {
    name: 'Classic Chicken Caesar Salad',
    category: 'International Dishes',
    subcategory: 'Salad',
    country: 'United States',
    caloriesPer100: 145,
    proteinPer100: 12.5,
    carbsPer100: 4.2,
    fatPer100: 8.8,
    fiberPer100: 1.2,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'bowl', multiplier: 2.8 }]),
    isIndian: false,
    isVeg: false,
    notes: 'Romaine lettuce, grilled chicken breast, shaved parmesan, garlic croutons and Caesar dressing.',
  },
  {
    name: 'Original Smokehouse Beef Jerky',
    category: 'Protein',
    subcategory: 'Meat',
    country: 'United States',
    caloriesPer100: 410,
    proteinPer100: 33.2,
    carbsPer100: 11.0,
    fatPer100: 25.6,
    fiberPer100: 1.8,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'piece', multiplier: 0.28 }, { unit: 'bag', multiplier: 0.85 }]),
    isIndian: false,
    isVeg: false,
    notes: 'Dehydrated, cured lean beef slices; indestructible high-protein travel snack.',
  },
  {
    name: 'Pure Protein / Quest Bar (Chocolate Brownie)',
    category: 'Snacks',
    subcategory: 'Supplements',
    country: 'United States',
    caloriesPer100: 333,
    proteinPer100: 35.0,
    carbsPer100: 36.7,
    fatPer100: 11.7,
    fiberPer100: 23.3,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'bar', multiplier: 0.60 }]),
    isIndian: false,
    isVeg: true,
    notes: '1 bar (~60g) provides 200 kcal, 21g whey/milk protein and 14g prebiotic fiber.',
  },
  {
    name: 'Almond Butter (100% Roasted Almonds)',
    category: 'Snacks',
    subcategory: 'Nut Butters',
    country: 'United States',
    caloriesPer100: 614,
    proteinPer100: 21.0,
    carbsPer100: 18.8,
    fatPer100: 55.5,
    fiberPer100: 10.5,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'tablespoon', multiplier: 0.16 }]),
    isIndian: false,
    isVeg: true,
    notes: 'Smooth roasted almond butter with zero added oil; high magnesium and Vitamin E.',
  },

  // --- ITALY EXPANSION ---
  {
    name: 'Gnocchi alla Sorrentina (Potato Dumplings with Mozzarella)',
    category: 'International Dishes',
    subcategory: 'Pasta',
    country: 'Italy',
    caloriesPer100: 165,
    proteinPer100: 6.5,
    carbsPer100: 24.0,
    fatPer100: 5.2,
    fiberPer100: 1.8,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'plate', multiplier: 2.8 }]),
    isIndian: false,
    isVeg: true,
    notes: 'Soft potato gnocchi baked with tomato passata, fresh basil and melted mozzarella.',
  },
  {
    name: 'Bruschetta al Pomodoro e Basilico',
    category: 'International Dishes',
    subcategory: 'Antipasti',
    country: 'Italy',
    caloriesPer100: 175,
    proteinPer100: 4.8,
    carbsPer100: 26.0,
    fatPer100: 6.2,
    fiberPer100: 2.2,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'piece', multiplier: 0.65 }]),
    isIndian: false,
    isVeg: true,
    notes: 'Toasted rustic bread rubbed with garlic and topped with ripe tomatoes, olive oil and basil (~115 kcal).',
  },
  {
    name: 'Bistecca alla Fiorentina (Florentine T-Bone Steak)',
    category: 'Protein',
    subcategory: 'Meat',
    country: 'Italy',
    caloriesPer100: 235,
    proteinPer100: 27.5,
    carbsPer100: 0.0,
    fatPer100: 14.0,
    fiberPer100: 0.0,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'portion', multiplier: 3.5 }]),
    isIndian: false,
    isVeg: false,
    notes: 'Thick cut Tuscan Chianina T-bone steak grilled over hardwood coals with sea salt and olive oil.',
  },
  {
    name: 'Panna Cotta with Berry Coulis',
    category: 'Snacks',
    subcategory: 'Dessert',
    country: 'Italy',
    caloriesPer100: 220,
    proteinPer100: 3.5,
    carbsPer100: 21.0,
    fatPer100: 14.0,
    fiberPer100: 0.5,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'piece', multiplier: 1.2 }]),
    isIndian: false,
    isVeg: true,
    notes: 'Piedmontese chilled sweetened cream dessert set with gelatin and topped with tart berry puree.',
  },

  // --- MEXICO EXPANSION ---
  {
    name: 'Tacos al Pastor (Marinated Pork & Pineapple, 2 Tacos)',
    category: 'International Dishes',
    subcategory: 'Tacos',
    country: 'Mexico',
    caloriesPer100: 210,
    proteinPer100: 14.5,
    carbsPer100: 17.5,
    fatPer100: 9.5,
    fiberPer100: 2.0,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'piece', multiplier: 0.85 }, { unit: 'serving', multiplier: 1.7 }]),
    isIndian: false,
    isVeg: false,
    notes: 'Achiote-marinated spit-roasted pork with cilantro, onions and caramelized pineapple in corn tortillas.',
  },
  {
    name: 'Crispy Baja Fish Tacos (with Cabbage Slaw)',
    category: 'International Dishes',
    subcategory: 'Tacos',
    country: 'Mexico',
    caloriesPer100: 195,
    proteinPer100: 12.0,
    carbsPer100: 19.5,
    fatPer100: 7.8,
    fiberPer100: 2.2,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'piece', multiplier: 0.90 }]),
    isIndian: false,
    isVeg: false,
    notes: 'Battered crispy white fish in warm corn tortillas topped with chipotle crema and lime slaw.',
  },
  {
    name: 'Mexican Refried Pinto Beans (Frijoles Refritos)',
    category: 'Carbohydrates',
    subcategory: 'Legumes',
    country: 'Mexico',
    caloriesPer100: 125,
    proteinPer100: 6.5,
    carbsPer100: 18.0,
    fatPer100: 3.2,
    fiberPer100: 6.0,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'cup', multiplier: 2.0 }, { unit: 'bowl', multiplier: 1.8 }]),
    isIndian: false,
    isVeg: true,
    notes: 'Mashed pinto beans cooked with onions, garlic and spices; rich in soluble fiber.',
  },

  // --- JAPAN EXPANSION ---
  {
    name: 'Spicy Tuna Roll (6 pieces)',
    category: 'International Dishes',
    subcategory: 'Sushi',
    country: 'Japan',
    caloriesPer100: 185,
    proteinPer100: 10.5,
    carbsPer100: 24.0,
    fatPer100: 5.5,
    fiberPer100: 1.2,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'piece', multiplier: 0.30 }, { unit: 'roll', multiplier: 1.8 }]),
    isIndian: false,
    isVeg: false,
    notes: 'Fresh diced tuna tossed with sriracha and sesame oil rolled with nori and sushi rice.',
  },
  {
    name: 'Chicken Katsu Curry with Rice',
    category: 'International Dishes',
    subcategory: 'Curry',
    country: 'Japan',
    caloriesPer100: 195,
    proteinPer100: 11.5,
    carbsPer100: 23.5,
    fatPer100: 6.8,
    fiberPer100: 1.8,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'plate', multiplier: 3.5 }]),
    isIndian: false,
    isVeg: false,
    notes: 'Crispy panko-breaded chicken cutlet with rich savory Japanese curry sauce over white rice.',
  },
  {
    name: 'Agedashi Tofu (Crispy Silken Tofu in Dashi)',
    category: 'Protein',
    subcategory: 'Tofu',
    country: 'Japan',
    caloriesPer100: 115,
    proteinPer100: 8.5,
    carbsPer100: 6.5,
    fatPer100: 6.2,
    fiberPer100: 1.2,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'bowl', multiplier: 1.8 }]),
    isIndian: false,
    isVeg: true,
    notes: 'Lightly potato-starch dusted fried silken tofu served in hot savory dashi broth with grated daikon.',
  },

  // --- CHINA EXPANSION ---
  {
    name: 'Peking Roast Duck (with Mandarin Pancakes)',
    category: 'International Dishes',
    subcategory: 'Meat',
    country: 'China',
    caloriesPer100: 290,
    proteinPer100: 18.5,
    carbsPer100: 6.5,
    fatPer100: 21.0,
    fiberPer100: 0.5,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'pancake wrap', multiplier: 0.75 }]),
    isIndian: false,
    isVeg: false,
    notes: 'Crisp roasted duck skin and meat wrapped in thin pancakes with hoisin sauce and scallions.',
  },
  {
    name: 'General Tso’s Crispy Chicken',
    category: 'International Dishes',
    subcategory: 'Poultry',
    country: 'China',
    caloriesPer100: 235,
    proteinPer100: 15.0,
    carbsPer100: 19.5,
    fatPer100: 11.0,
    fiberPer100: 0.8,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'plate', multiplier: 2.8 }]),
    isIndian: false,
    isVeg: false,
    notes: 'Crispy fried chicken tossed in sweet, tangy and mildly spicy ginger-soy glaze.',
  },
  {
    name: 'Dim Sum Har Gow (Crystal Shrimp Dumplings, 4 pcs)',
    category: 'International Dishes',
    subcategory: 'Dim Sum',
    country: 'China',
    caloriesPer100: 160,
    proteinPer100: 11.2,
    carbsPer100: 21.0,
    fatPer100: 3.5,
    fiberPer100: 0.6,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'piece', multiplier: 0.25 }, { unit: 'basket', multiplier: 1.0 }]),
    isIndian: false,
    isVeg: false,
    notes: 'Translucent steamed wheat-tapioca starch parcels packed with fresh whole shrimp (~40 kcal per piece).',
  },

  // --- MIDDLE EAST EXPANSION ---
  {
    name: 'Charcoal Lamb Shish Kebab (2 skewers)',
    category: 'Protein',
    subcategory: 'Meat',
    country: 'Middle East',
    caloriesPer100: 230,
    proteinPer100: 25.0,
    carbsPer100: 1.2,
    fatPer100: 14.5,
    fiberPer100: 0.2,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'skewer', multiplier: 0.80 }, { unit: 'serving', multiplier: 1.6 }]),
    isIndian: false,
    isVeg: false,
    notes: 'Marinated cubed lamb skewered with onions and peppers, grilled over glowing hardwood charcoal.',
  },
  {
    name: 'Baba Ganoush (Smoked Roasted Eggplant Dip)',
    category: 'International Dishes',
    subcategory: 'Dips',
    country: 'Middle East',
    caloriesPer100: 110,
    proteinPer100: 2.5,
    carbsPer100: 7.8,
    fatPer100: 8.5,
    fiberPer100: 3.8,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'tablespoon', multiplier: 0.30 }, { unit: 'bowl', multiplier: 1.5 }]),
    isIndian: false,
    isVeg: true,
    notes: 'Charred smoked eggplant blended with sesame tahini, garlic, lemon juice and olive oil.',
  },
  {
    name: 'Grilled Halloumi Cheese (Cyprus)',
    category: 'Dairy',
    subcategory: 'Cheese',
    country: 'Middle East',
    caloriesPer100: 320,
    proteinPer100: 22.0,
    carbsPer100: 1.8,
    fatPer100: 25.0,
    fiberPer100: 0.0,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'slice', multiplier: 0.40 }]),
    isIndian: false,
    isVeg: true,
    notes: 'High-melting point sheep and goat milk cheese pan-seared until golden brown (~128 kcal per slice).',
  },

  // --- THAILAND EXPANSION ---
  {
    name: 'Pad See Ew (Wide Rice Noodles with Pork & Chinese Broccoli)',
    category: 'International Dishes',
    subcategory: 'Noodles',
    country: 'Thailand',
    caloriesPer100: 175,
    proteinPer100: 9.2,
    carbsPer100: 23.0,
    fatPer100: 5.5,
    fiberPer100: 1.8,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'plate', multiplier: 3.0 }]),
    isIndian: false,
    isVeg: false,
    notes: 'Broad flat rice noodles stir-fried in a hot wok with dark soy, sliced pork, egg and gai lan.',
  },
  {
    name: 'Som Tum (Thai Spicy Green Papaya Salad)',
    category: 'Vegetables',
    subcategory: 'Salad',
    country: 'Thailand',
    caloriesPer100: 65,
    proteinPer100: 2.2,
    carbsPer100: 11.5,
    fatPer100: 1.5,
    fiberPer100: 2.8,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'bowl', multiplier: 2.0 }]),
    isIndian: false,
    isVeg: true,
    notes: 'Shredded green unripe papaya pounded with bird’s eye chillies, lime, garlic, green beans and crushed peanuts.',
  },
  {
    name: 'Mango Sticky Rice (Khao Niew Mamuang)',
    category: 'Snacks',
    subcategory: 'Dessert',
    country: 'Thailand',
    caloriesPer100: 215,
    proteinPer100: 2.8,
    carbsPer100: 38.0,
    fatPer100: 6.5,
    fiberPer100: 1.2,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'portion', multiplier: 2.2 }]),
    isIndian: false,
    isVeg: true,
    notes: 'Sweet glutinous rice steamed in coconut milk served with ripe sweet yellow champagne mango.',
  },

  // --- KOREA EXPANSION ---
  {
    name: 'Samgyeopsal (Thick Grilled Pork Belly)',
    category: 'Protein',
    subcategory: 'Meat',
    country: 'Korea',
    caloriesPer100: 330,
    proteinPer100: 17.5,
    carbsPer100: 0.0,
    fatPer100: 29.0,
    fiberPer100: 0.0,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'serving', multiplier: 1.5 }]),
    isIndian: false,
    isVeg: false,
    notes: 'Tabletop grilled thick pork belly strips wrapped in fresh perilla leaves with ssamjang.',
  },
  {
    name: 'Tteokbokki (Spicy Chewy Rice Cakes in Gochujang)',
    category: 'International Dishes',
    subcategory: 'Street Food',
    country: 'Korea',
    caloriesPer100: 180,
    proteinPer100: 4.2,
    carbsPer100: 36.5,
    fatPer100: 2.0,
    fiberPer100: 1.8,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'bowl', multiplier: 2.5 }]),
    isIndian: false,
    isVeg: true,
    notes: 'Chewy cylindrical rice cakes simmered in sweet and spicy gochujang chili broth with scallions and fish cakes.',
  },
  {
    name: 'Japchae (Sweet Potato Glass Noodles with Beef)',
    category: 'International Dishes',
    subcategory: 'Noodles',
    country: 'Korea',
    caloriesPer100: 165,
    proteinPer100: 5.8,
    carbsPer100: 26.5,
    fatPer100: 4.5,
    fiberPer100: 2.0,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'plate', multiplier: 2.5 }]),
    isIndian: false,
    isVeg: false,
    notes: 'Translucent chewy sweet potato starch noodles stir-fried with spinach, carrots, mushrooms, beef and sesame oil.',
  },

  // --- UNITED KINGDOM EXPANSION ---
  {
    name: 'Bangers and Mash with Onion Gravy',
    category: 'International Dishes',
    subcategory: 'Meat',
    country: 'United Kingdom',
    caloriesPer100: 185,
    proteinPer100: 7.8,
    carbsPer100: 16.5,
    fatPer100: 10.2,
    fiberPer100: 1.5,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'plate', multiplier: 3.5 }]),
    isIndian: false,
    isVeg: false,
    notes: 'Pan-seared Cumberland pork sausages served over buttery mashed potatoes with rich caramelized onion gravy.',
  },
  {
    name: 'Beef Wellington (Tenderloin in Mushroom Duxelles)',
    category: 'International Dishes',
    subcategory: 'Meat',
    country: 'United Kingdom',
    caloriesPer100: 275,
    proteinPer100: 21.0,
    carbsPer100: 12.5,
    fatPer100: 16.0,
    fiberPer100: 1.0,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'slice', multiplier: 2.0 }]),
    isIndian: false,
    isVeg: false,
    notes: 'Seared beef fillet wrapped in mushroom duxelles, prosciutto and golden crisp puff pastry.',
  },

  // --- FRANCE EXPANSION ---
  {
    name: 'French Onion Soup Gratinée (with Gruyère Toast)',
    category: 'International Dishes',
    subcategory: 'Soup',
    country: 'France',
    caloriesPer100: 95,
    proteinPer100: 4.8,
    carbsPer100: 9.5,
    fatPer100: 4.5,
    fiberPer100: 1.5,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'bowl', multiplier: 3.0 }]),
    isIndian: false,
    isVeg: false,
    notes: 'Slow-caramelized yellow onions simmered in rich beef broth, baked with a floating toasted baguette and molten Gruyère.',
  },
  {
    name: 'Crispy French Baguette (Artisanal)',
    category: 'Carbohydrates',
    subcategory: 'Breads',
    country: 'France',
    caloriesPer100: 265,
    proteinPer100: 9.0,
    carbsPer100: 53.0,
    fatPer100: 1.2,
    fiberPer100: 2.8,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'serving', multiplier: 0.60 }]),
    isIndian: false,
    isVeg: true,
    notes: 'Traditional French bread with crisp golden crust and light airy crumb; low fat.',
  },

  // --- GREECE EXPANSION ---
  {
    name: 'Lamb Gyro Wrap (with Fries & Tzatziki in Pita)',
    category: 'International Dishes',
    subcategory: 'Street Food',
    country: 'Greece',
    caloriesPer100: 215,
    proteinPer100: 12.8,
    carbsPer100: 22.0,
    fatPer100: 8.8,
    fiberPer100: 2.0,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'wrap', multiplier: 2.5 }]),
    isIndian: false,
    isVeg: false,
    notes: 'Spit-roasted spiced lamb shavings stuffed into warm pita with tomatoes, red onions, crisp fries and tzatziki (~540 kcal).',
  },
  {
    name: 'Moussaka (Eggplant, Beef & Béchamel Bake)',
    category: 'International Dishes',
    subcategory: 'Bakes',
    country: 'Greece',
    caloriesPer100: 175,
    proteinPer100: 9.2,
    carbsPer100: 11.5,
    fatPer100: 10.5,
    fiberPer100: 2.5,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'piece', multiplier: 2.8 }]),
    isIndian: false,
    isVeg: false,
    notes: 'Layers of roasted eggplant, spiced cinnamon beef ragù and fluffy baked golden béchamel cream.',
  },

  // --- SPAIN EXPANSION ---
  {
    name: 'Patatas Bravas (Crispy Potatoes with Spicy Tomato Aioli)',
    category: 'International Dishes',
    subcategory: 'Tapas',
    country: 'Spain',
    caloriesPer100: 185,
    proteinPer100: 3.2,
    carbsPer100: 24.5,
    fatPer100: 8.5,
    fiberPer100: 2.8,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'plate', multiplier: 2.0 }]),
    isIndian: false,
    isVeg: true,
    notes: 'Fried potato cubes dressed in smoky spicy pimentón sauce and garlic aioli.',
  },
  {
    name: 'Gambas al Ajillo (Sizzling Garlic & Chili Shrimp)',
    category: 'Protein',
    subcategory: 'Seafood',
    country: 'Spain',
    caloriesPer100: 155,
    proteinPer100: 19.5,
    carbsPer100: 1.5,
    fatPer100: 8.0,
    fiberPer100: 0.2,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'cazuela', multiplier: 1.8 }]),
    isIndian: false,
    isVeg: false,
    notes: 'Plump shrimp flash-sautéed in extra virgin olive oil with minced garlic and red dried chillies.',
  },

  // --- BRAZIL & LATIN AMERICA EXPANSION ---
  {
    name: 'Pão de Queijo (Warm Brazilian Tapioca Cheese Puffs)',
    category: 'Snacks',
    subcategory: 'Breads',
    country: 'Brazil',
    caloriesPer100: 295,
    proteinPer100: 7.5,
    carbsPer100: 36.0,
    fatPer100: 14.0,
    fiberPer100: 0.8,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'piece', multiplier: 0.30 }]),
    isIndian: false,
    isVeg: true,
    notes: 'Gluten-free Brazilian cheese puffs made from sour cassava tapioca flour and cured Minas cheese (~88 kcal per puff).',
  },
  {
    name: 'Peruvian Ceviche Clásico (Fresh Fish in Leche de Tigre)',
    category: 'Protein',
    subcategory: 'Seafood',
    country: 'Brazil',
    caloriesPer100: 95,
    proteinPer100: 16.5,
    carbsPer100: 4.5,
    fatPer100: 1.0,
    fiberPer100: 0.8,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'bowl', multiplier: 2.2 }]),
    isIndian: false,
    isVeg: false,
    notes: 'Ultra-fresh sea bass cured in fresh lime juice with red onions, cilantro and aji amarillo.',
  },

  // --- GERMANY EXPANSION ---
  {
    name: 'Grilled Thüringer Bratwurst with Spicy Mustard',
    category: 'Protein',
    subcategory: 'Meat',
    country: 'Germany',
    caloriesPer100: 295,
    proteinPer100: 14.0,
    carbsPer100: 1.5,
    fatPer100: 26.0,
    fiberPer100: 0.0,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'piece', multiplier: 1.2 }]),
    isIndian: false,
    isVeg: false,
    notes: 'German pork sausage seasoned with marjoram, caraway and garlic, grilled crispy (~350 kcal).',
  },
  {
    name: 'Berliner Currywurst with Spiced Curry Ketchup',
    category: 'International Dishes',
    subcategory: 'Street Food',
    country: 'Germany',
    caloriesPer100: 240,
    proteinPer100: 11.5,
    carbsPer100: 12.0,
    fatPer100: 16.5,
    fiberPer100: 1.0,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'portion', multiplier: 2.2 }]),
    isIndian: false,
    isVeg: false,
    notes: 'Steamed then fried pork sausage smothered in warm spiced curry-tomato sauce.',
  },

  // --- VIETNAM EXPANSION ---
  {
    name: 'Phở Gà (Vietnamese Chicken Noodle Soup)',
    category: 'International Dishes',
    subcategory: 'Soup',
    country: 'Vietnam',
    caloriesPer100: 85,
    proteinPer100: 7.2,
    carbsPer100: 12.0,
    fatPer100: 1.2,
    fiberPer100: 0.8,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'bowl', multiplier: 4.5 }]),
    isIndian: false,
    isVeg: false,
    notes: 'Steaming chicken broth infused with charred ginger and coriander seeds with shredded chicken breast and rice noodles.',
  },
  {
    name: 'Bánh Mì Thịt Nướng (Vietnamese Baguette with Grilled Pork & Pâté)',
    category: 'International Dishes',
    subcategory: 'Street Food',
    country: 'Vietnam',
    caloriesPer100: 215,
    proteinPer100: 12.8,
    carbsPer100: 26.0,
    fatPer100: 7.2,
    fiberPer100: 2.2,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'sandwich', multiplier: 2.2 }]),
    isIndian: false,
    isVeg: false,
    notes: 'Crispy airy French baguette stuffed with lemongrass grilled pork, liver pâté, pickled daikon-carrot and cucumber (~470 kcal).',
  },

  // --- GLOBAL WHOLE FOODS EXPANSION ---
  {
    name: 'Raw Shelled Pumpkin Seeds (Pepitas)',
    category: 'Snacks',
    subcategory: 'Seeds',
    country: 'Global',
    caloriesPer100: 559,
    proteinPer100: 30.2,
    carbsPer100: 10.7,
    fatPer100: 49.0,
    fiberPer100: 6.0,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'tablespoon', multiplier: 0.15 }, { unit: 'handful', multiplier: 0.30 }]),
    isIndian: false,
    isVeg: true,
    notes: 'Superfood for male hormonal health; supreme natural source of zinc and magnesium.',
  },
  {
    name: 'Raw Shelled Hemp Hearts',
    category: 'Snacks',
    subcategory: 'Seeds',
    country: 'Global',
    caloriesPer100: 553,
    proteinPer100: 31.6,
    carbsPer100: 8.7,
    fatPer100: 48.8,
    fiberPer100: 4.0,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'tablespoon', multiplier: 0.15 }]),
    isIndian: false,
    isVeg: true,
    notes: 'Complete plant protein with perfect 3:1 Omega-6 to Omega-3 essential fatty acid ratio.',
  },
  {
    name: 'Medjool Dates (Pitted)',
    category: 'Fruits',
    subcategory: 'Dried Fruit',
    country: 'Global',
    caloriesPer100: 277,
    proteinPer100: 1.8,
    carbsPer100: 75.0,
    fatPer100: 0.2,
    fiberPer100: 6.7,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'piece', multiplier: 0.24 }]),
    isIndian: false,
    isVeg: true,
    notes: 'Nature’s energy booster: 1 large date (~24g) has ~66 kcal of fast-absorbing natural glucose/fructose.',
  },
  {
    name: 'Fresh Green Asparagus Spears',
    category: 'Vegetables',
    subcategory: 'Stems',
    country: 'Global',
    caloriesPer100: 20,
    proteinPer100: 2.2,
    carbsPer100: 3.9,
    fatPer100: 0.1,
    fiberPer100: 2.1,
    servingUnits: JSON.stringify([{ unit: 'g', multiplier: 1 }, { unit: 'spear', multiplier: 0.16 }, { unit: 'cup', multiplier: 1.34 }]),
    isIndian: false,
    isVeg: true,
    notes: 'Natural diuretic rich in asparagine and glutathione; classic bodybuilding cutting vegetable.',
  },
];

async function run() {
  console.log('🔄 Merging existing master foods with expansion list...');
  const foodMap = new Map<string, MasterFoodItem>();

  for (const f of existingFoods) {
    foodMap.set(f.name.toLowerCase().trim(), f);
  }

  for (const f of expansionFoods) {
    foodMap.set(f.name.toLowerCase().trim(), f);
  }

  const combinedFoods = Array.from(foodMap.values());
  console.log(`✨ Total Master Foods compiled: ${combinedFoods.length}`);

  // 1. Write the updated master-foods-data.ts file
  const fileHeader = `export interface MasterFoodItem {
  name: string;
  category: string;
  subcategory?: string;
  country: string;
  caloriesPer100: number;
  proteinPer100: number;
  carbsPer100: number;
  fatPer100: number;
  fiberPer100: number;
  servingUnits: string;
  isIndian: boolean;
  isVeg: boolean;
  notes?: string;
}

export const COUNTRY_METADATA: Record<string, { name: string; flag: string; region: string }> = {
  All: { name: 'All Cuisines', flag: '🌍', region: 'Global' },
  India: { name: 'India', flag: '🇮🇳', region: 'South Asia' },
  'United States': { name: 'USA & Gym Staples', flag: '🇺🇸', region: 'North America' },
  Italy: { name: 'Italy', flag: '🇮🇹', region: 'Europe' },
  Mexico: { name: 'Mexico', flag: '🇲🇽', region: 'Americas' },
  Japan: { name: 'Japan', flag: '🇯🇵', region: 'East Asia' },
  China: { name: 'China', flag: '🇨🇳', region: 'East Asia' },
  'Middle East': { name: 'Middle East', flag: '🇱🇧', region: 'Middle East' },
  Thailand: { name: 'Thailand', flag: '🇹🇭', region: 'Southeast Asia' },
  Korea: { name: 'Korea', flag: '🇰🇷', region: 'East Asia' },
  'United Kingdom': { name: 'United Kingdom', flag: '🇬🇧', region: 'Europe' },
  France: { name: 'France', flag: '🇫🇷', region: 'Europe' },
  Greece: { name: 'Greece', flag: '🇬🇷', region: 'Mediterranean' },
  Spain: { name: 'Spain', flag: '🇪🇸', region: 'Europe' },
  Brazil: { name: 'Brazil & Latin America', flag: '🇧🇷', region: 'South America' },
  Germany: { name: 'Germany', flag: '🇩🇪', region: 'Europe' },
  Vietnam: { name: 'Vietnam', flag: '🇻🇳', region: 'Southeast Asia' },
  Global: { name: 'Global Whole Foods', flag: '🥗', region: 'Worldwide' },
};

export const MASTER_FOODS: MasterFoodItem[] = ${JSON.stringify(combinedFoods, null, 2)};
`;

  const outputPath = path.join(process.cwd(), 'lib/nutrition/master-foods-data.ts');
  fs.writeFileSync(outputPath, fileHeader, 'utf-8');
  console.log(`✅ Successfully updated ${outputPath} with ${combinedFoods.length} master foods!`);

  // 2. Upsert each food into the Supabase database
  console.log('🚀 Seeding database with Master Food Base in batches...');
  let createdCount = 0;
  let updatedCount = 0;

  for (const food of combinedFoods) {
    const existing = await prisma.food.findFirst({
      where: { name: food.name },
    });

    if (existing) {
      await prisma.food.update({
        where: { id: existing.id },
        data: {
          category: food.category,
          subcategory: food.subcategory,
          country: food.country,
          caloriesPer100: food.caloriesPer100,
          proteinPer100: food.proteinPer100,
          carbsPer100: food.carbsPer100,
          fatPer100: food.fatPer100,
          fiberPer100: food.fiberPer100,
          servingUnits: food.servingUnits,
          isIndian: food.isIndian,
          isVeg: food.isVeg,
          notes: food.notes,
        },
      });
      updatedCount++;
    } else {
      await prisma.food.create({
        data: food,
      });
      createdCount++;
    }
  }

  console.log(`🎉 Database seeding finished! Created: ${createdCount}, Updated: ${updatedCount}, Total in DB: ${createdCount + updatedCount}`);
}

run()
  .catch(console.error)
  .finally(async () => {
    await prisma.$disconnect();
  });
